"""tts.* orchestration tests with a fake engine manager (no models, no GPU)."""
from __future__ import annotations

from pathlib import Path

import pytest
import soundfile as sf

from shadowfetch_worker.protocol import CANCELLED, ENGINE_CRASHED, INVALID_PARAMS, CancelledError, WorkerError
try:  # tests/ is a package when tests/__init__.py exists (rootdir import mode), a plain dir otherwise
    from tests.test_store import FakeEngineManager, call, fake_caps, install_fake_audio, make_ctx, make_server, make_voice
except ImportError:  # pragma: no cover
    from test_store import FakeEngineManager, call, fake_caps, install_fake_audio, make_ctx, make_server, make_voice

SCRIPT = "The first sentence is here. The second sentence is here.\n\nA new paragraph starts now. It has 2 sentences."


@pytest.fixture
def server(tmp_path, monkeypatch):
    install_fake_audio(monkeypatch)
    return make_server(tmp_path)


def make_project(server, script=SCRIPT, **opts):
    v = make_voice(server)
    p = call(server, "projects.create", {"name": "Story", "voice_id": v["id"], "script_text": script})
    plan = call(server, "tts.plan", {"project_id": p["id"], "engine_id": "fake-engine", "options": {"max_chars": 40, **opts}})
    return v, p, plan


# ---------------------------------------------------------------- plan
def test_plan_stores_segments_and_options(server):
    v, p, plan = make_project(server, spell_numbers=True)
    assert plan["plan_version"] == 1 and plan["engine_id"] == "fake-engine" and plan["script_version"] == 1
    texts = [s["text"] for s in plan["segments"]]
    assert texts == ["The first sentence is here.", "The second sentence is here.", "A new paragraph starts now.", "It has 2 sentences."]
    assert [s["paragraph"] for s in plan["segments"]] == [0, 0, 1, 1]
    assert plan["segments"][3]["normalized_text"] == "It has two sentences."
    assert all(not s["reused"] and s["take_count"] == 0 for s in plan["segments"])
    view = call(server, "projects.get", {"id": p["id"]})
    assert [s["text"] for s in view["segments"]] == texts and view["project"]["plan_version"] == 1
    assert view["project"]["settings"]["plan"]["max_chars"] == 40 and view["project"]["settings"]["plan"]["spell_numbers"] is True
    # engine limit clamps: the fake engine allows 200 chars
    r = call(server, "tts.plan", {"project_id": p["id"], "options": {"max_chars": 1000}})
    assert any("engine limit" in w for w in r["warnings"]) and r["plan_version"] == 2
    with pytest.raises(WorkerError) as ei:
        call(server, "tts.plan", {"project_id": call(server, "projects.create", {"name": "empty"})["id"]})
    assert ei.value.code == INVALID_PARAMS


def test_plan_reuses_segment_ids_across_edits(server):
    v, p, plan = make_project(server)
    ids = {s["text"]: s["id"] for s in plan["segments"]}
    gen = call(server, "tts.generate", {"project_id": p["id"]})
    assert len(gen["takes"]) == 4
    edited = SCRIPT.replace("The second sentence is here.", "The second sentence changed.")
    plan2 = call(server, "tts.plan", {"project_id": p["id"], "script_text": edited})
    assert plan2["plan_version"] == 2 and plan2["script_version"] == 2
    by_text = {s["text"]: s for s in plan2["segments"]}
    for t in ("The first sentence is here.", "A new paragraph starts now.", "It has 2 sentences."):
        assert by_text[t]["id"] == ids[t] and by_text[t]["reused"] and by_text[t]["take_count"] == 1 and by_text[t]["selected_take_id"]
    changed = by_text["The second sentence changed."]
    assert changed["id"] not in ids.values() and not changed["reused"] and changed["selected_take_id"] is None
    # the old segment keeps its take (history) so reverting the edit brings the take back
    db = server.state["db"]
    assert db.one("SELECT plan_version FROM segments WHERE id = ?", (ids["The second sentence is here."],))["plan_version"] == 1
    plan3 = call(server, "tts.plan", {"project_id": p["id"], "script_text": SCRIPT})
    back = {s["text"]: s for s in plan3["segments"]}["The second sentence is here."]
    assert back["id"] == ids["The second sentence is here."] and back["take_count"] == 1
    # old-plan segments without takes are pruned
    assert db.one("SELECT COUNT(*) AS n FROM segments WHERE id = ?", (changed["id"],))["n"] == 0
    # only the segment without a take is generated by default
    plan4 = call(server, "tts.plan", {"project_id": p["id"], "script_text": edited})
    gen2 = call(server, "tts.generate", {"project_id": p["id"]})
    assert [t["segment_index"] for t in gen2["takes"]] == [1] and sorted(gen2["skipped"]) == [0, 2, 3]
    assert plan4["plan_version"] == 4


# ---------------------------------------------------------------- generate
def test_generate_writes_takes_and_progress(server):
    v, p, plan = make_project(server)
    eng = server.state["engines"]
    ctx = make_ctx(server, "tts.generate")
    res = call(server, "tts.generate", {"project_id": p["id"], "settings": {"temperature": 0.7}, "seed": 100, "take_label": "v1"}, ctx=ctx)
    assert len(res["takes"]) == 4 and res["skipped"] == [] and res["model_revision"] == "rev1" and res["prompt_cache_id"]
    for i, t in enumerate(res["takes"]):
        assert t["segment_index"] == i and Path(t["path"]).exists() and t["seed"] == 100 + i
        assert p["id"] in t["path"] and t["segment_id"] in t["path"] and t["path"].endswith(f"{t['take_id']}.wav")
        assert sf.info(t["path"]).samplerate == 24000 and abs(sf.info(t["path"]).duration - t["duration_s"]) < 0.01
    msgs = [m["message"] for m in server.transport.progress() if m["stage"] == "generate"]
    assert msgs == [f"Generating segment {i} of 4" for i in range(1, 5)]
    gen_msgs = [m for m in server.transport.progress() if m["stage"] == "generate"]
    assert gen_msgs[2]["current"] == 3 and gen_msgs[2]["total"] == 4 and gen_msgs[2]["detail"]["segment_index"] == 2
    # the engine received normalized text, the derived reference, the transcript and the prompt cache
    assert [c["text"] for c in eng.calls] == [s["normalized_text"] for s in plan["segments"]]
    assert all(c["settings"] == {"temperature": 0.7} and c["language"] == "en" and c["prompt"] for c in eng.calls)
    assert eng.calls[0]["reference_path"].endswith("reference.fake-engine.wav") and len(eng.prepared) == 1
    view = call(server, "projects.get", {"id": p["id"]})
    for s in view["segments"]:
        assert len(s["takes"]) == 1 and s["selected_take_id"] == s["takes"][0]["id"] and s["takes"][0]["label"] == "v1"
        assert s["takes"][0]["status"] == "ok" and s["takes"][0]["settings"] == {"temperature": 0.7}
    assert view["project"]["settings"]["controls"]["fake-engine"] == {"temperature": 0.7} and view["project"]["settings"]["seed"] == 100
    assert server.state["settings"].value.engine_settings["fake-engine"] == {"temperature": 0.7}
    # prompt cache row exists and is reused on the next run (no second prepare)
    db = server.state["db"]
    rows = db.all("SELECT * FROM prompt_cache")
    assert len(rows) == 1 and Path(rows[0]["path"]).exists() and rows[0]["model_revision"] == "rev1"
    res2 = call(server, "tts.generate", {"project_id": p["id"], "segment_indices": [2]})
    assert [t["segment_index"] for t in res2["takes"]] == [2] and len(eng.prepared) == 1 and res2["skipped"] == [0, 1, 3]
    seg2 = call(server, "projects.get", {"id": p["id"]})["segments"][2]
    assert len(seg2["takes"]) == 2 and seg2["selected_take_id"] == res2["takes"][0]["take_id"]
    # regenerate_all makes a take for every segment
    res3 = call(server, "tts.generate", {"project_id": p["id"], "regenerate_all": True})
    assert len(res3["takes"]) == 4


def test_generate_rejects_undeclared_controls_and_bad_indices(server):
    v, p, plan = make_project(server)
    with pytest.raises(WorkerError) as ei:
        call(server, "tts.generate", {"project_id": p["id"], "settings": {"speed": 1.2}})
    assert ei.value.code == INVALID_PARAMS and "speed" in ei.value.message
    with pytest.raises(WorkerError) as ei:
        call(server, "tts.generate", {"project_id": p["id"], "settings": {"temperature": 9}})
    assert ei.value.code == INVALID_PARAMS
    with pytest.raises(WorkerError) as ei:
        call(server, "tts.generate", {"project_id": p["id"], "segment_indices": [0, 9]})
    assert ei.value.code == INVALID_PARAMS and ei.value.details["bad_indices"] == [9]
    with pytest.raises(WorkerError) as ei:
        call(server, "tts.generate", {"project_id": p["id"], "language": "xx"})
    assert ei.value.code == INVALID_PARAMS
    assert server.state["engines"].calls == []
    # no reference -> clear error
    q = call(server, "projects.create", {"name": "no voice", "script_text": "Hello there."})
    call(server, "tts.plan", {"project_id": q["id"], "engine_id": "fake-engine"})
    with pytest.raises(WorkerError) as ei:
        call(server, "tts.generate", {"project_id": q["id"]})
    assert ei.value.code == INVALID_PARAMS and "reference" in ei.value.message


def test_generate_without_reusable_prompt_or_seed(tmp_path, monkeypatch):
    install_fake_audio(monkeypatch)
    eng = FakeEngineManager([fake_caps(supports_reusable_prompt=False, supports_seed=False)])
    server = make_server(tmp_path, eng)
    v, p, plan = make_project(server)
    res = call(server, "tts.generate", {"project_id": p["id"], "seed": 5})
    assert res["prompt_cache_id"] is None and eng.prepared == [] and all(c["prompt"] is None for c in eng.calls)
    assert all(c["seed"] is None for c in eng.calls) and any("seed" in w for w in res["warnings"])
    assert server.state["db"].one("SELECT COUNT(*) AS n FROM prompt_cache")["n"] == 0


def test_cancel_mid_run_keeps_completed_takes(tmp_path, monkeypatch):
    install_fake_audio(monkeypatch)
    eng = FakeEngineManager(cancel_after=2)
    server = make_server(tmp_path, eng)
    v, p, plan = make_project(server)
    ctx = make_ctx(server, "tts.generate")
    with pytest.raises(CancelledError) as ei:
        call(server, "tts.generate", {"project_id": p["id"]}, ctx=ctx)
    err = ei.value
    assert err.code == CANCELLED and len(err.details["completed"]) == 2 and err.details["failed_segment"] == 2
    assert len(eng.calls) == 2
    view = call(server, "projects.get", {"id": p["id"]})
    assert [len(s["takes"]) for s in view["segments"]] == [1, 1, 0, 0]
    assert all(Path(t["path"]).exists() for t in err.details["completed"])
    # resuming generates only the two missing segments
    eng.cancel_after = None
    res = call(server, "tts.generate", {"project_id": p["id"]})
    assert [t["segment_index"] for t in res["takes"]] == [2, 3] and res["skipped"] == [0, 1]


def test_engine_failure_keeps_completed_takes(tmp_path, monkeypatch):
    install_fake_audio(monkeypatch)
    eng = FakeEngineManager(fail_on_text="new paragraph")
    server = make_server(tmp_path, eng)
    v, p, plan = make_project(server)
    with pytest.raises(WorkerError) as ei:
        call(server, "tts.generate", {"project_id": p["id"]})
    assert ei.value.code == ENGINE_CRASHED and ei.value.details["failed_segment"] == 2
    assert [t["segment_index"] for t in ei.value.details["completed"]] == [0, 1]
    assert server.state["db"].one("SELECT COUNT(*) AS n FROM takes")["n"] == 2


# ---------------------------------------------------------------- assemble
def test_assemble_master(server):
    v, p, plan = make_project(server)
    with pytest.raises(WorkerError) as ei:
        call(server, "tts.assemble", {"project_id": p["id"]})
    assert ei.value.code == INVALID_PARAMS and ei.value.details["missing_segments"] == [0, 1, 2, 3]
    gen = call(server, "tts.generate", {"project_id": p["id"]})
    res = call(server, "tts.assemble", {"project_id": p["id"], "sentence_pause_ms": 100, "paragraph_pause_ms": 500})
    master = Path(res["master_path"])
    assert master.name == "master.wav" and master.exists() and res["segments_used"] == 4 and res["sample_rate"] == 24000
    takes_total = sum(t["duration_s"] for t in gen["takes"])
    expected = takes_total + 2 * 0.1 + 0.5
    assert abs(res["duration_s"] - expected) < 0.02 and abs(sf.info(str(master)).duration - expected) < 0.02
    proj = call(server, "projects.get", {"id": p["id"]})["project"]
    assert proj["master_path"] == str(master) and proj["master"]["take_ids"] == [t["take_id"] for t in gen["takes"]]
    assert proj["settings"]["plan"]["sentence_pause_ms"] == 100
    # explicit take selection override + a stale id is rejected
    alt = call(server, "tts.generate", {"project_id": p["id"], "segment_indices": [0]})["takes"][0]
    res2 = call(server, "tts.assemble", {"project_id": p["id"], "take_selection": {"0": gen["takes"][0]["take_id"]}})
    assert call(server, "projects.get", {"id": p["id"]})["project"]["master"]["take_ids"][0] == gen["takes"][0]["take_id"] != alt["take_id"]
    with pytest.raises(WorkerError):
        call(server, "tts.assemble", {"project_id": p["id"], "take_selection": {"1": "take_nope"}})
    assert res2["segments_used"] == 4 and not (master.parent / "master.tmp.wav").exists()


# ---------------------------------------------------------------- compare
def test_compare_engines_sequential(tmp_path, monkeypatch):
    install_fake_audio(monkeypatch)
    eng = FakeEngineManager([fake_caps("engine-a"), fake_caps("engine-b", supports_reusable_prompt=False)])
    server = make_server(tmp_path, eng)
    v = make_voice(server)
    p = call(server, "projects.create", {"name": "Cmp", "voice_id": v["id"], "script_text": "One. Two."})
    call(server, "tts.plan", {"project_id": p["id"], "engine_id": "engine-a"})
    res = call(server, "tts.compare_engines", {"project_id": p["id"], "engine_ids": ["engine-a", "engine-b", "engine-x"], "segment_index": 0,
                                               "settings": {"engine-b": {"temperature": 0.5}}})
    ok = [r for r in res["results"] if "error" in r]
    assert [r["engine_id"] for r in res["results"]] == ["engine-a", "engine-b", "engine-x"] and ok[0]["engine_id"] == "engine-x"
    assert eng.load_order == ["engine-a", "engine-b"]
    for r in res["results"][:2]:
        assert Path(r["path"]).exists() and Path(r["loudness_matched_preview_path"]).exists()
        assert Path(r["loudness_matched_preview_path"]).parent == server.state["paths"].tmp
    assert eng.calls[1]["settings"] == {"temperature": 0.5} and eng.calls[0]["settings"] == {}
    # generated takes are stored but not auto-selected; originals untouched by the preview copy
    seg = call(server, "projects.get", {"id": p["id"]})["segments"][0]
    assert len(seg["takes"]) == 2 and seg["selected_take_id"] is None and {t["label"] for t in seg["takes"]} == {"compare:engine-a", "compare:engine-b"}
    assert Path(res["results"][0]["path"]).read_bytes() == Path(res["results"][0]["loudness_matched_preview_path"]).read_bytes()
